#pragma once

#define RCGP_CONTRACT_FROM_NAME(name) , contract <name> name
#define RCGP_CONTRACT_FROM_TUPLE(name, ref) , contract <(ref)> name

#define RCGP_CONTRACT_IS_ENABLE_IF(tag, ...) \
	MACRO_CHECK(MACRO_CAT(RCGP_CONTRACT_IS_ENABLE_IF_PROBE_, tag))
#define RCGP_CONTRACT_IS_ENABLE_IF_PROBE_ENABLE_IF MACRO_PROBE()

#define RCGP_CONTRACT_ENABLE_IF_TUPLE(cond, name, ref) \
	, std::conditional_t <cond, contract <(ref)>, jems::null> name
#define RCGP_CONTRACT_ENABLE_IF_NAME(cond, name) \
	, std::conditional_t <cond, contract <name>, jems::null> name

#define RCGP_CONTRACT_FROM_ENABLE_IF(tag, cond, arg) \
	RCGP_CONTRACT_FROM_ENABLE_IF_ARG(cond, arg)
#define RCGP_CONTRACT_ENABLE_IF_TUPLE_WRAPPER(cond, arg) \
	MACRO_APPLY(RCGP_CONTRACT_ENABLE_IF_TUPLE, (cond, MACRO_UNPACK arg))
#define RCGP_CONTRACT_ENABLE_IF_NAME_WRAPPER(cond, arg) \
	RCGP_CONTRACT_ENABLE_IF_NAME(cond, arg)
#define RCGP_CONTRACT_FROM_ENABLE_IF_ARG(cond, arg) \
	MACRO_IF(MACRO_IS_PAREN(arg))	\
	(	\
		RCGP_CONTRACT_ENABLE_IF_TUPLE_WRAPPER,	\
		RCGP_CONTRACT_ENABLE_IF_NAME_WRAPPER	\
	)(cond, arg)

#define RCGP_CONTRACT_FROM_ENABLE_IF_WRAPPER(...) \
	RCGP_CONTRACT_FROM_ENABLE_IF(__VA_ARGS__)
#define RCGP_CONTRACT_FROM_TUPLE_WRAPPER(...) \
	RCGP_CONTRACT_FROM_TUPLE(__VA_ARGS__)
#define RCGP_CONTRACT_FROM_PAREN(...) \
	MACRO_IF(RCGP_CONTRACT_IS_ENABLE_IF(__VA_ARGS__)) \
	(	\
		RCGP_CONTRACT_FROM_ENABLE_IF_WRAPPER, \
		RCGP_CONTRACT_FROM_TUPLE_WRAPPER \
	)(__VA_ARGS__)

#define RCGP_CONTRACT_FROM_ARG(arg) \
	MACRO_IF(MACRO_IS_PAREN(arg))(RCGP_CONTRACT_FROM_PAREN arg, RCGP_CONTRACT_FROM_NAME(arg))
#define CONTRACT_GENERATOR(ctx, arg) RCGP_CONTRACT_FROM_ARG(arg)
